List<List<String>> hintMatrix = [
  ['English',
    "The first dictionary for this language was written in 1755.",
    "1/4 of the world’s population speaks at least some of this language.",
    "Over 80% of the information stored on computers worldwide is in this language.",
    "The most commonly used noun is 'time'.",
    "This language is the official language of 67 countries.",
    "90% of texts written in this language consists of just 1000 words.",
    "The oldest word in this language that is still in use is 'town'.",
    "The two most common words in this language are 'I' and 'you'.",
    "11% of the entire language is just the letter 'E'.",
    "About 4,000 words are added to the dictionary each year.",
  ],
  ['Spanish',
    "This language is the most romantic language.",
    "This language is second most spoken language in the world.",
    "Arabic has big influence on this language.",
    "This language and English are from the same language family.",
    "This language is the 3rd most used language on the internet.",
    "This language is the second most studied language.",
    "First grammar for this language Wws published in 1492.",
    "15.8% countries use this language as their official language.",
    "Castilian is another name of this language.",
    "This language is the fastest language spoken.",
  ],
  ['French',
    "This language a Romance language.",
    "There are around 220 million speakers worldwide.",
    "This language has a great number of homophones.",
    "About 45% of modern English words are of this language's origin.",
    "Along with English, this language remains an influential language in the diplomatic world.",
    "This language is the official language of 29 countries.",
    "This language is a good second language for polyglots.",
    "This language is one of the easiest languages for English speakers to learn.",
    "This language and ballet go hand in hand.",
    "This language is used widely in the United States as well.",
  ],
  ['Italian',
    "This language became an official language in 1861.",
    "The alphabet of this language only has 21 letters.",
    "This language is considered one of the closest languages to Latin.",
    "Some words from this language are misused in English.",
    "Approximately 66 million people speak this language worldwide.",
    "Over 700,000 Americans speak this language.",
    "The word ‘Volt‘ was created in this language.",
    "This language loves double consonants.",
    "The longest word in this language contains 30 letters: 'psiconeuroendocrinoimmunologia'.",
    "The word ‘America’ comes from this language.",
  ],
  ['Russian',
    "There are around 154 million native speakers.",
    "This language is the eighth most-spoken language in the world.",
    "This language is the official language in 4 countries.",
    "This language is derived from Old East Slavic.",
    "This language is the language of space.",
    "This language's nouns have genders.",
    "This language is written using the Cyrillic alphabet.",
    "This language has less than half the number of words as English."
    "Text translated from English to this language usually expands by around 15%.",
    "This language is the most widespread language in Eurasia.",
  ],
  ['Romanian',
    "This language is 1,700 years old.",
    "It’s the only Romance language that prevailed in Eastern Europe.",
    "You can understand this language if you’ve studied other Romance languages.",
    "There are four dialects spoken in the Balkanic countries.",
    "You’ve surely heard the famous song 'Dragostea din tei'.",
    "About 24 million people speak it as a native language, and 4 million people speak it as a second language.",
    "This language is easy to read or pronounce, since it is a phonetic language.",
    "This language has 66% Latin-based words and 20% Slavic-based words.",
    "There are 5 special letters in this language.",
    "When learning this language, you may have difficulty with the grammar.",
  ],
  ['Portuguese',
    "This language is a Romance language.",
    "This language is ranked as the sixth most natively spoken language in the world.",
    "This language has some popular tongue twisters.",
    "This language has influenced English and other Western languages.",
    "Until recently, the letters 'k', 'y' and 'w' were absent from this language's alphabet.",
    "There are over 250 million speakers around the globe.",
    "It’s the official language of nine countries.",
    "It’s the fastest-growing European language in the world behind English.",
    "This language is heavily influenced by Arabic.",
    "This language comes from Galicia in Northwest Spain.",
  ],
  ['Dutch',
    "This language is a Germanic language.",
    "The first official spelling guide for this language was written in 1804.",
    "The French language was a big influence on this language for a long time.",
    "There are a lot of different dialects and accents. (200 - 600)",
    "The longest word in this language has 53 letters.",
    "This language is full of consonants.",
    "This language has the weirdest proverbs in the world.",
    "This language is also spoken in Belgium, South America, Latin America, South Africa, Indonesia.",
    "This language has a word that can not be translated: 'Gezellig'.",
    "Almost 95% of the native speakers of this language, also speak English.",
  ],
  ['German',
    "The longest word in this language has 79 letters.",
    "130 million people speak this language as their mother tongue or as a second language.",
    "The words in this language have three genders.",
    "Time is counted with reference to the upcoming hour.",
    "English and this language share 60% of their vocabulary.",
    "All nouns are capitalised in this language.",
    "Some speakers of this language have trouble understanding one another.",
    "This language is the most common native language in the European Union.",
    "This language is part of the West Germanic languages, along with English and Dutch.",
    "Until the mid-20th century, this language was written using a different script of the Latin alphabet.",
  ],
  ['Swedish',
    "This language is a North Germanic language derived from Old Norse.",
    "There are around 9 million native speakers across the world.",
    "Several words from this language made it into the English language.",
    "This language shares similarities with Danish and Norwegian.",
    "This language has only been the official language of a nordic country since 2009.",
    "In this language, the days of the week are named after Nordic Gods.",
    "This language has nine vowels – or 18.",
    "You get to learn Danish and Norwegian when learning this language.",
    "This language are three characters in the Swedish language that are not used in English.",
    "The longest word in this language contains 28 letters.",
  ],
  ['Albanian',
    "This language is not closely related to any other language.",
    "There are six million native speakers in the Balkans.",
    "The two major spoken dialects of this language: Tosk and Gheg.",
    "This country has only existed since the 15th century.",
    "The official standard dialect for this language has been Tosk since 1969.",
    "There have been many calls to reform this standard language in recent times.",
    "This language used to be mistaken as a Romance language.",
    "This language is the mother tongue of around seven million people worldwide.",
    "This language is amongst the oldest in Europe and even in the world.",
    "This language is the official language Kosovo and a co-official language in North Macedonia.",
  ],
  ['Catalan',
    "This language is a Romance language derived from Vulgar Latin.",
    "This language is spoken by an estimated 9 million people.",
    "This language has been banned and repressed several times during its long history.",
    "This language has six dialects, from East to West.",
    "This language has more in common with French and Italian than with Spanish.",
    "The closest relative of this language is Occitan.",
    "This language it’s also the official language in Andorra.",
    "This language it’s not a dialect of Spanish.",
    "This language has more in common with Gallo-Romance languages than Ibero-Romance languages.",
    "This language has about as many speakers as Swedish.",
  ],
  ['Polish',
    "This language is a Slavic language.",
    "There are around 55 million speakers across the world.",
    "The longest word in this language contains 54 letters.",
    "This country is close to Czech, Slovak, and Sorbian languages.",
    "According to the UK 2011 census, this language is the second most spoken language in England and Wales.",
    "This language is generally assumed to be one of the hardest languages to learn.",
    "It is safe to say that nearly every word in this language has at least one diminutive form.",
    "This language evolved from the Indo-European languages and finally took a form in the tenth century.",
    "There are 32 letters in this language's alphabet.",
    "This language comes in fourteen different grammatical formations and pronunciation.",
  ],
  ['Czech',
    "This language is one of the West Slavic languages.",
    "There are around 10 million speakers in the world.",
    "This language used to be known as Bohemian.",
    "Some words in this language don’t have any vowels.",
    "This language almost disappeared in the 17th century.",
    "This language is the only officially recognized language to use 'ř'.",
    "This language is mutually intelligible with Slovak.",
    "Adding '-ovat' is a nifty way of turning English verbs into this language's verbs.",
    "This language's alphabet has 42 letters.",
    "This language doesn't have a variation for the word 'kangaroo'.",
  ],
  ['Turkish',
    "This language is part of the Turkic languages.",
    "This language has around 75 million native speakers.",
    "Before 1928, this language was written using a specific form of Arabic writing.",
    "This language has been strongly influenced by Farsi, Arabic, and French.",
    "This language is spoken natively in two continents (but only one country).",
    "More people speak this language than Italian and Greek combined.",
    "This language completely revamped its alphabet in 1932.",
    "This language originally came from Siberia.",
    "There are 29 letters in this language's alphabet (21 consonants and 8 vowels).",
    "This language is one of the globe’s 15 most widely spoken first languages.",
  ],
  ['Finnish',
    "This language has one of the world’s longest words, the biggest word has 61 letters.",
    "This language has a reputation for being challenging for foreigners to learn (maybe impossible).",
    "There is no future tense in this language.",
    "This language is close to Hungarian and Estonian.",
    "This language is art of the Uralic language family.",
    "In this language, one word can express a whole sentence in English.",
    "This language formed the basis of the Elvish language of Quenya in Lord of the Rings.",
    "Mikael Agricola is the father of this language.",
    "In this language, there’s no word for 'please'.",
    "This language holds the Guinness World Record for the world’s longest palindrome.",
  ],
  ['Norwegian',
    "This language is a North Germanic language.",
    "There are around 5 million native speakers.",
    "This language has two official forms of written language.",
    "This language shares similarities with Danish and Swedish.",
    "This language is a Scandinavian Language.",
    "This language is a tonal language.",
    "In this language there are so many different dialects.",
    "English is influencing this language a lot!",
    "This language is one of the working languages of the Nordic Council.",
    "Reading this language is like reading English.",
  ],
  ['Danish',
    "This language is a North Germanic language.",
    "This language is spoken by around 6 million speakers.",
    "This language is very similar to Swedish and Norwegian.",
    "There are three extra vowels in this language compared to English: Æ, Ø and Å.",
    "Just like German,this language's words can be added together to form very long words.",
    "This language is an official language in Greenland.",
    "In this language there are two genders, but they’re not masculine and feminine,they are common and neuter.",
    "In this language, counting is based on the number 20.",
    "This language introduced a new letter only 60 years ago: å.",
    "This language is not generally harder than languages like German, French or English."
  ],
  ['Greek',
    "This language is a Hellenic language.",
    "There are around 13 million native speakers.",
    "The word 'alphabet' refers to the first two letters of this language's alphabet.",
    "The longest word ever to appear in literature is in this language and it has a whopping 171 letters.",
    "Until 1976, there were two different official versions of this language.",
    "In this language, the question mark looks like a semicolon.",
    "This language was originally written from right to left.",
    "The latin, coptic and cyrillic alphabets (among others) are based on this language's alphabet.",
    "This language is one of the oldest documented living languages in the indo-european language family.",
    "Vowels were first used in this language's alphabet.",
  ],
  ['Korean',
    "This language is an isolate ont, it has no significant link to any other existing language on Earth.",
    "This language's vocabulary is heavily influenced by Chinese.",
    "In this country there are two different counting systems.",
    "This language had no alphabet until the 15th century.",
    "In this language, the shape of the letters mimic your tongue movement.",
    "This language has its own script, called Hangul.",
    "It is spoken by  80 million people worldwide, making it the world’s 13th most widely spoken language.",
    "This language's alphabet only has  24 letters.",
    "This language's alphabet (Hangul) can be learned in only 90 minutes.",
    "This language has several dialects: Hamgyong, Pyongan, Central dialects, Jeolla, Gyeongsang.",
  ],
  ['Japanese',
    "In the native tongue, it’s actually called 'Nihongo'.",
    "Even though this language uses Chinese characters, the language isn’t based on Chinese.",
    "In this language there are no plurals.",
    "In this language there are no articles.",
    "In this language intonation does matter.",
    "This language is one of the most fast-paced spoken languages in the world.",
    "Despite popular belief, this language has no genetic relation to Chinese.",
    "This language is the ninth most commonly spoken language in the entire world.",
    "This language uses 4 writing systems: Kanji, Hiragana, Katakana, Romaji.",
    "In this language there are different formality levels.",
  ],
  ['Chinese',
    "With over a billion native speakers, about 15% of the world’s population speaks this language as their mother tongue.",
    "This language doesn't have an alphabet.",
    "In this language nouns don’t have a singular/plural distinction.",
    "In this language different tones can drastically change a word’s meaning.",
    "There are over 20,000 distinct characters in this language.",
    "This language's writing system is over 3,000 years old.",
    "It is considered One of the hardest languages to learn.",
    "This language has different calligraphy styles.",
    "The handwriting of this language is the most unrecognizable.",
    "This language is one of the oldest languages still in use.",
  ],
  ['Mandarin',
    "This one is the most popular Chinese dialect.",
    "This language is a major language in Southeast Asian countries.",
    "This is now the number one dialect in New York’s Chinatown.",
    "This language has no alphabet.",
    "This language is one of the fastest growing languages in the World.",
    "Around 1 billion people speak this language around the world.",
    "This language is mostly spoken in China, Taiwan, Singapore, and Malaysia.",
    "This language has four tones.",
    "This one started developing 1,000 years ago.",
    "This language is one the of Chinese language forms which develop from the regional variants of Middle Chinese.",
  ],
  ['Indonesian',
    "This language is widely spoken in all countries of Southern Asia.",
    "This language is the 9th most spoken language in the world.",
    "This language is part of the Malayan language.",
    "This language is the second language in Vietnam.",
    "This language is a popular one in Australia.",
    "This language is the third most used language in WordPress.",
    "This language has been strongly influenced by Arabic.",
    "There is almost no gender in this language.",
    "This language is a standardized variety of Malay, an Austronesian language.",
    "This language is not the mother tongue of one of big ethnic groups in Indonesia.",
  ],
  ['Bulgarian',
    "Together with Macedonian, the languages are somewhat unique in the Slavic group.",
    "This language is widely spoken in other countries as well, like Albania, Romania, Czech, Serbia, and Ukraine.",
    "Of the Slavic languages, this language was the first one written down.",
    "This language could be considered the original Slavic language.",
    "You can easily confuse this language with Bulgar.",
    "This language has Nine Tenses.",
    "This language belongs to the Indo –European language family.",
    "Overall there are around 15 Million speakers of this language in the world.",
    "The Bulgarian language is known to be closely related to the Macedonian language.",
    "The longest word in this language is a 39-letter-long word: 'непротивоконституционствувателствувайте'.",
  ],
  ['Hindi',
    "This language is an Indo-European language.",
    "Hindi is spoken by 366 million people across the world.",
    "This language is also spoken in Mauritius, Fiji, Guyana, Suriname, Trinidad & Tobago and Nepal.",
    "This language is 5th most spoken language in the world.",
    "This language has some similarities with the languages like Urdu, Bengali, Sanskrit, Nepalese, and Gujarati.",
    "If you know this language, you’ll be able to communicate in Urdu also.",
    "If you know this language, you can easily read the Nepalese language.",
    "Words like ‘yoga’, ‘karma’, ‘khaki’, ‘pyjama’, and ‘mantra’ are taken from this language.",
    "The majority of this language's speakers are found in India’s northern half.",
    "This language is a mix of Arabic and Persian words. More than 5,500 words in the dictionary are of Perso-Arabic origin.",
  ],
  ['Bengali',
    "The Indian national anthem was first written in this language.",
    "This language arose from the eastern Middle Indic languages of the Indian subcontinent, such as Pāli, and Sanskrit.",
    "This language is an honorary official language in Sierra Leone.",
    "This language is the second most spoken language in India.",
    "Both the national anthems of Bangladesh and India were composed in Bengali.",
    "The International Mother Language day is based on this language.",
    "This language is the seventh most spoken language by over 215 million people around the world.",
    "This language is one of the most beautiful spoken languages in the world as it is rich in emotional expressions.",
    "There are no gender specific pronouns in this language, but it does have gender-specific terms like 'mother' and 'father'.",
    "This language is the official language of Bangladesh.",
  ],
  ['Hungarian',
    "Magyar is the real term for this language.",
    "This is one of the hardest language to learn in the world.",
    "Only 13 million people around the world speak this language.",
    "This language has similarities with Finnish.",
    "The country where this language is spoken is very close to Romania.",
    "This language comes from the Uralic region of Asia and belongs to the Finno-Ugric language group.",
    "There are 44 words in the longest word of this language's dictionary.",
    "In this language we can distinguish 14 vowels in both the short and long versions: a-á, e-é, i-í, o-ó, ö-ő, u-ú, ü-ű.",
    "Dominik Szoboszlai, the football player, speaks this languague",
    "This language it is also spoken in Slovakia, Ukraine, Transylvania, Serbia, Croatia, Slovenia and Austria.",
  ],
  ['Arabic',
    "This language originates from the Arabian Peninsula.",
    "Arabic is an official language in 26 countries, including Algeria, Egypt, Israel, Lebanon, Saudi Arabia, Tunisia and UAE.",
    "This language and Hebrew are both Semitic languages.",
    "The words in this language are written from right to left, and the numbers are written from left to right.",
    "This language is the 5th most spoken language worldwide.",
    "This language has almost 700 million speakers.",
    "In this language there are around 14 words that describe 'love'.",
    "This language has influenced many other languages around the globe, especially languages of Muslim cultures.",
    "This language is thought to be the language with the richest vocabulary.",
    "It is estimated that more than 150 million people are called Mohammed in the country where this language is mostly spoken.",
  ],
  ['Estonian',
    "The first book written in this language was printed in 1535.",
    "This language is a Finno-Ugric Language.",
    "This language has 8 dialects and 117 subdialects.",
    "This language is considerably easier for a Finnish speaker.",
    "This language is strongly influenced by German.",
    "This language has been named the world's 5th toughest language to learn after Japanese, Chinese, Korean and Arabic.",
    "This language has no gender or future tense.",
    "This language subclassified as a Southern Finnic language.",
    "Despite being a Baltic country, this language has nothing in common with Latvian or Lithuanian.",
    "There are still around 20,000 speakers (that’s over half a percent!) in various villages in Siberia.",
  ],
];
