List<List<String>> languageMatrix = [
  ['English',
    "I stated an opinion on what happened.",
    "Be very careful with the path that you choose to take.",
    "Your mission is not just difficult, it is impossible.",
    "Barry Allen's movement is the fastest on the planet.",
    "A lot of water is flowing throughout the ship.",
    "I guess I'll be living with you a year from now.",
    "Tom is eager to buy a new car.",
    "I lost my key somewhere around here.",
    "All I have is books.",
    "	Do you like the new school better?",
  ],
  ['Spanish',
    "Me encanta vuestra melena rubia.",
    "¿Le queda alguna habitación por la noche?",
    "La farmacia abre a las ocho de la mañana.",
    "Quiero dos tarjetas, por favor.",
    "Os gustáis salie en balandro.",
    "Es un capitulo extra que solo está disponible en la versión de audio.",
    "De postre quiero flan.",
    "¿Hay coche-comedor en el tren?",
    "¿Cuánto tiempo dure el viaje?",
    "Quizá podemos ir la seman proxima.",
  ],
  ['French',
    "J'étais assise avec ma cigarette à la main et je me suis rendu compte que je préférerais t'avoir toi dans la main.",
    "Quiconque a peint cette maison etait aveugle.",
    "Qu'est ce que tu fais si je t'embrasse maintenant?",
    "D'accord, tu peux rester près de moi tant que tu ne parles pas de la chaleur qu'il fait ici.",
    "Comme dessert, que me suggereriez-vous pour effacer le goût du plat de resistance de ma bouche?",
    "Mon verre s'ennuie tout seul. Est-ce que votre verre veut bien le rejoindre?",
    "J'étais assise avec ma cigarette à la main et je me suis rendu compte que je préférerais t'avoir toi dans la main.",
    "Le réalité et toi, vous ne vous entendez pas, n'est-ce pas?",
    "Excusez-moi, ça ne vous embête pas que je vous observe une minute? Je veux me souvenir de votre visage pour mes rêves.",
    "Si je te donne mon numéro de téléphone, tu le gardes ou tu le jettes?",
  ],
  ['Italian',
    "Finché c’è vita c’è speranza.",
    "Sin che si vive, s’impara sempre.",
    "La vita è fatta a scale: c’è chi scende e c’è chi sale.",
    "Chi vive vede molto, chi viaggia vede di più.",
    "La vita è già mezzo trascorsa anziché si sappia che cosa sia.",
    "Se vuoi vivere cent’anni senza pene, prendi il mondo come viene.",
    "Questo non è ciò che ho ordinato.",
    "Qualcuno può portarmi gentilmente le valigie su?",
    "Il forte vento ha abbattuto l'albero.",
    "Vorrei una bistecca per secondo.",
  ],
  ['Russian',
    "Она ровесница твоей мамы.",
    "Если интересно, в школе есть программа, по которой можно стажироваться у доктора и получить знания в сфере медицины.",
    "В период кризиса необходим пересмотр многих позиций и адаптация к новым реалиям бизнес-среды.",
    "Твоё сочинение очень хорошее, и в нем мало ошибок.",
    "Это экологически устойчивый материал, который никогда не иссякнет.",
    "Я дам вам наркоз, и пока вам будут сниться приятные сны, разберусь со всем.",
    "Это настоящая интеграция человека с машиной.",
    "В общей сумме призовой фонд составляет 10818 евро.",
    "Это поэтично, дьявольски выражаясь.",
    "Тебе нужно ехать домой и лечиться.",
  ],
  ['Romanian',
    "Mă duc la bunici să vorbesc cu ei.",
    "Tocmai ce am ajuns acasă din excursie cu clasa.",
    "Mi se pare mie sau vremea s-a încălzit foarte tare astazi.",
    "Ceea ce îmi place cel mai mult la această casă este priveliștea pe care o am asupra orașului.",
    "Emisiunea la care m-am uitat seara trecută a fost una foarte frumoasă.",
    "Mâine seară vom merge în oraș să ne uităm la un meci de fotbal.",
    "În limba romnană există anumite expresii care nu se pot traduce în altă limbă.",
    "Emoția pe care o primești la terminarea liceului nu poate fi descrisă în cuvinte.",
    "Unii oameni nu pleacă vara la mare, ci la munte.",
    "Patul de la hotel a fost foarte mic.",
  ],
  ['Portuguese',
    "Você ainda tem o dinheiro dela.",
    "Ele prefere falar com as três garotas aí.",
    "Ela não gosta das praias do Rio tanto como as do Recife.",
    "Tomara que você tenha tempo suficiente.",
    "Esse arroz é encantado, quem comer dele acaba sendo rico.",
    "Há muitas marcas imitando o tipo de embalagem do café Melita.",
    "Nós ficaremos juntos até as 6:00.",
    "Você é do Rio de Janeiro, né?",
    "Você não me conhece menina, tenho poderes extras-terrenos.",
    "Vamos ver se ele telefona para você.",
    "Eu só podia comer um ovo.",
    "Zora Ionara é a maior astróloga do Brasil.",
    "Estou trabalhando por Marcos hoje porque ele está doente.",
    "Acho que somos quase da mesma idade.",
    "Você se lembra do teu primeiro namorado?",
    "Ele bateu o carro dele outro dia.",
    "Não quero que o Leandro esteja com esse azar nos jogos.",
    "Alguns motoristas estão cobrando 10% a mais, e não devem.",
    "Não sei porque eles estão demorando tanto.",
    "O lobo não comerá mais crianças na floresta.",
    "Seus convidados vão adorar os presentes de casamento que comprei.",
    "Nesse restaurante ainda fazem a comida italiana como antigamente.",
    "Vamos falar com mais um dos rapazes daquele bairro.",
    "Eu daria o mundo inteiro para ter você comigo por um instante.",
    "Espero que vocês estejam super felizes com o carro.",
    "Os que foram as montanhas ficaram doentes.",
    "É ridiculo dançar sozinho.",
    "Acho que meus primos vem da Europa.",
    "Ultimamente os rapazes tem jogado muita bola.",
    "Seria uma tragédia se a televisão não funcionasse durante o jogo.",
    "Quando era menino sempre gostava de sorvete.",
    "Prefiro o vinho branco quando tiver a opção.",
    "Explicou as regras para que todo mundo entendesse.",
    "O médico recomendou que eu dormisse um pouco mais.",
    "Se você quiser, eu posso comprar umas flores e chocolates.",
    "Estamos contentes, é um prazer estar aqui.",
    "O curso poderá ser frequentado por períodos diferentes.",
    "Se você pudesse organizar tudo com a Ana, seria muito melhor.",
    "Depois de completar as tarefas, posso começar com a segunda parte.",
    "Andrea pediu que a gente ficasse um pouco mais.",
    "Talvez a gente tenha que ajudar aos animais que estão aí também.",
    "Quando lhe dei as flores, ela jogou tudo na minha cara.",
    "Se o Beto fizesse isso, já não considero ele meu filho mais.",
    "O menino comeu uma formiga e nem fez questão do negócio.",
    "Que dia mais lindo, eu nunca vi o céu tão azul.",
    "É importante que Amélia diga tudo que sabe do caso.",
    "Quando Carlos trouxer o bolo, poderemos começar com a festa.",
    "Sherlock Holms era mais inteligente do que o próprio Perry Mason.",
    "O feijão vai secar se vocês não puserem mais agua na panela.",
    "Graças a Deus, é o fim dessas frases brasileiras."
  ],
  ['Dutch',
    "Wou je dat even schrijven alstublieft.",
    "Ik ben zeer slecht in Natuurkunde.",
    "Hoe laat vertrekt de volgende trein naar Oegstgeest?",
    "Wat denk je over de stuk?",
    "Ik heb een tafel gereserveerd voor de naam Jansen.",
    "Naar welke balie zou ik gaan om geld te wisselen?",
    "Ik denk dat er een foutje zit in de afrekening.",
    "Ik wil deze week graag gaan kamperen met mijn vrienden.",
    "Kun je geloven dat ze daadwerkelijk uit elkaar zijn gegaan?",
    "Er is niemand op deze planeet die deze vergelijking kan oplossen.",
  ],
  ['German',
    "Für alle Arten des Angelns ist in Florida eine Erlaubnis erforderlich.",
    "Versuchen Sie rund 500 Kalorien pro Tag verbrennen, indem Sie Aerobic und verschiedene Übungen.",
    "Wir wissen nicht mit Sicherheit, dass Jethro Hanson anfiel.",
    "Nach solchen Angebern werden die Puppen und Videospiele benannt.",
    "Anmeldestart für Aussteller ist Anfang Februar 2019.",
    "Das machte sie auch bei mir, um mich anzuturnen.",
    "Die darunterliegenden Äderchen werden dort leichter sichtbar als in anderen Bereichen.",
    "Ich persönlich glaube, dass nur ein Leben in Luxus lebten führt zu einer schrittweisen Abkehr von Alltagsrealität.",
    "Beschleunigung des eigenen Audit- und Analyseprozesses, um zu verbessernde Bereiche zu ermitteln und zu dokumentieren.",
    "Sagen wir einfach mal, dass ich nicht Insolvenz anmelde.",
  ],
  ['Swedish',
    "Kulturen och människorna var mycket intressanta.",
    "Jag skulle älska att besöka ditt land igen.",
    "Glöm inte att skriva till mig då och då.",
    "Vad är namnet på denna maträtt?",
    "Jag har en reservation (för ett rum).",
    "Var finns närmaste apotek?",
    "Jag behöver en läkare.",
    "Hur lång tid tar det att komma dit?",
    "Hur kan jag komma till (den här platsen, staden)?",
    "Du har inte en accent.",
  ],
  ['Albanian',
    "Do t'ju pëlqente të kërcenit?",
    "Do martoheni me mua?",
    "Kjo është një ditë e bukur.",
    "Ka kaq shumë yje.",
    "Duhet të përdor kompjuterin.",
    "Kam nevojë të shkoj të fle.",
    "A ka ndonjë varkë që mund të na çojë atje?",
    "Si mund të shkoj në atë ishull të largët, afër Italisë?",
    "A keni lidhje me familjen në atë shtëpi?",
    "Nuk më pëlqen kur duhet të shkoj në punë të premten.",
  ],
  ['Catalan',
    "Necessito medicaments per al dolor.",
    "Cordeu-vos el cinturó de seguretat.",
    "Sóc al·lèrgic a aliments diferents.",
    "Barcelona és una ciutat i metròpoli a la costa mediterrània de la península Ibèrica.",
    "L'educació serà gratuïta, si més no, en la instrucció elemental i fonamental.",
    "El pare i la mare tenen dret preferent d'escollir la mena d'educació que serà donada als seus fills.",
    "Sempre m'ha agradat anar als parcs d'atraccions.",
    "En el futur, m'agradaria ser un programador molt bo i conegut.",
    "Aquell senyor va dir que és hora de dirigir-se a la sortida, perquè la botiga estarà tancant.",
    "Vaig deixar la meva cartera a l'apartament del teu amic.",
  ],
  ['Polish',
    "Gry komputerowe mogą poprawić uwagę na szczegóły i pamięć.",
    "Kwiaty i drzewa zapewniają tlen, którego potrzebujemy do oddychania.",
    "Koty i psy są najpopularniejszymi zwierzętami na świecie.",
    "Tęcza zawsze pojawia się po mocnej burzy.",
    "Biblioteki zawierają informacje na temat wszelkich interesujących Cię kwestii.",
    "Rumunia ma najzapalszy budynek na świecie.",
    "Untikmed to jeden z najpopularniejszych w Rumunii festiwalu muzyki.",
    "Papugi mogą odtworzyć do 500 słów, które słyszą od ludzi.",
    "Twarde esencje przechowywane są w małych butelkach.",
    "Smoki były najpotężniejszymi istotami w Westerosie.",
  ],
  ['Czech',
    "Vánoce jsou pro Čechy nejvýznamnějším svátkem v roce.",
    "Ty v Čechách nosí pod ozdobený vánoční stromeček Ježíšek.",
    "Tak se mi zdá, že jsem dneska vstával levou nohou- to se tak říká, když se někomu celý den lepí smůla na paty.",
    "Doma na mě už čekala sousedka, které během dopoledne vytopil byt můj rozbitý mrazák.",
    "Středem města protéká řeka Vltava, po které se můžete vypravit na parníku do 5.",
    "V Praze je také mnoho divadel, kde pro velký zájem turistů hrají některé inscenace i v angličtině nebo němčině.",
    "Adéla by moc chtěla mít vlastního psa.",
    "Už má doma rybičky, k narozeninám slíbenou želvu a králíka.",
    "S rodiči se každý večer díváme na televizní zprávy, které začínají v osm hodin.",
    "Dále se mluvilo o stavbě nové dálnice za Prahou a také o ošklivé autonehodě u Brna.",
  ],
  ['Turkish',
    "Evde iki yatak odası, bir salon, bir banyo ve bir mutfak var.",
    "Büyük yatak odası mor ve gri, küçük yatak odası ise mavi ve yeşil.",
    "Evin yakınında toplu taşıma olsa da, yürümeyi sevdiğim için yürüyerek giderim.",
    "Öğleden sonra okul bitince, Kardelen ile birlikte eve döneriz.",
    "Sonbahar ve kış mevsimlerinde ise mandalina, portakal ve nar hasat ederiz.",
    "Bu ürünleri kendimiz yeriz ve komşularımızla paylaşırız.",
    "Bugün yapının üçüncü kata kadar olan kısmının Ceneviz, diğer katların Osmanlı karakteri taşıdığı gözlenmektedir.",
    "Silindirik gövdesi üzerindeki pencereler tuğla örgülü yuvarlak kemerlidir.",
    "Vapurla bu adalara seyahat ederken Marmara Denizi’ni seyre dalabilirsiniz.",
    "Eğer gerçek bir tarih, doğa ve kültür aşığı iseniz ve gezmek istiyorsanız İstanbul sizin için doğru adres.",
  ],
  ['Finnish',
    "Asun tyttöystäväni Maijan kanssa viisikerroksisessa kerrostalossa Helsingin Töölössä.",
    "Onneksi taloyhtiössä on sauna ja meillä on oma saunavuoro aina kerran viikossa, lauantaisin.",
    "Tutustuin Lauraan jo alakoulussa ja yhdessä meillä on aina tosi hauskaa!",
    "Hän on myös urheilullinen ja harrastaa eri urheilulajeja.",
    "Talli on bussipysäkin vieressä joten pääsen tallille kätevästi bussilla.",
    "Hän on sairas ja hän on tullut äitinsä kanssa käymään lääkärissä.",
    "Päänsärkyyn annan lääkettä, jota sinun tulee ottaa aamulla ja illalla, kahden päivän ajan.",
    "Bussissa istuessa hän kertaa usein suomen läksyjä tai lukee kirjaa.",
    "Tennistä pelatessa tulee aina kova hiki ja se on erinomaista liikuntaa.",
    "Joskus Lauran tytär Ellakin tulee mukaan saunaan ja istuu alalauteella.",
  ],
  ['Norwegian',
    "De snakker ofte om hvordan været er og skal bli.",
    "Når det er vinter i Norge er det mye snø noen år og lite snø andre år.",
    "Da kan det bli 25 grader og man kan bade og sole seg.",
    "De fleste i Norge spiser matretter fra hele verden, men to retter er typisk norsk.",
    "Lutefisk er torsk som først har blitt tørket og så legges den i kaldt vann med noe som heter lut.",
    "Lutefisken ser litt ut som gele og mange gruer seg for å smake på det.",
    "Ikke alle nordmenn liker matrettene heller.",
    "Hun følger listen mens hun starter å handle på matbutikken.",
    "Fordi ikke alle barnebarna hennes liker kjøttkaker, velger hun å også putte pølser og pølsebrød i handlevognen.",
    "Hun går derfor tilbake meieriproduktene og henter seg en kefir. ",
  ],
  ['Danish',
    "Maria har nu haft 3 års lektier, bøger og undervisning.",
    "Hver dag, glædet hun sig til at bestille sin mad i kantinen, sætte sig det samme sted og cykle forbi bageren.",
    "Hun har også nydt sine studiestunder med klassekammeraterne.",
    "Hvad ville de mennesker mene om nutidens livsstil?",
    "Selvom de første par dage, gik med at lære at holde balancen.",
    "Skiferie kan ikke sammenlignes med nogen anden slags ferie.",
    "Det er lørdag morgen klokken 9:30, og Marias lillebror ringer pludseligt.",
    "Hun laver en stor lasagne hver anden uge, og så fryser hun flere portioner, så hun altid har hendes yndlingsret klar.",
    "Hun bruger altid friske grøntsager når hun laver mad.",
    "Mest af alt hans viden, tid og kræfter.",
  ],
  ['Greek',
    "Ο υπολογιστής μου χάλασε την περασμένη εβδομάδα.",
    "Μην τον αφήσετε να ακούσει αυτή τη μουσική.",
    "Είναι ένα μοτίβο που επαναλαμβάνεται ξανά και ξανά από τότε που ο Τραμπ ξεκίνησε την προεδρική του υποψηφιότητα.",
    "Το αυτοκίνητό σας επισκευάζεται τώρα.",
    "Ο Ρούσβελτ προτείνει ότι μια ατομική βόμβα ήταν δυνατή και ότι η Γερμανία μπορεί να προσπαθεί να την κατασκευάσει.",
    "Οι μπότες είναι σφιχτές γύρω από τη γάμπα.",
    "Θέλετε να χορέψετε μαζί μου;",
    "Μία γλώσσα δεν είναι ποτέ αρκετή.",
    "Η κυρία θα πληρώσει για όλα.",
    "Νομίζω ότι ξέρεις ακριβώς για τι πράγμα μιλάω.",
  ],
  ['Korean',
    "그는 최고의 개인 조교 중 한 사람입니다.",
    "그는, 뉴욕에 있는 메네스 음대와 줄리아드 음대에서 음악 공부를 마쳤다.",
    "그녀가 돈을 다 잃었대, 불쌍한 사람.",
    "그 여름 별장은 소박한 목조 건축물이었다.",
    "그 아기는 48시간 동안 집중 치료실에 있었다.",
    "다행히도, 그는 업무를 성공적으로 해내고 있다.",
    "하사관이 신병들을 훈련시켰다.",
    "그녀는 5개 국어에 능통한 사람이다.",
    "중간 크기의 그릇에 커피를 녹여라.",
    "넌 내게 따스한 봄처럼 다가왔지.",
  ],
  ['Japanese',
    "ベティは立派な青年の結婚相手になれると思うよ。",
    "彼女は息子に似合いの結婚相手だ。",
    "逆もしかり　死刑反対の人もまた　同様の反応をします",
    "私はこう返した、もし嫌なら、あなたたちが軍司令官の所へ行くのね。",
    "ただし、高度な圧縮アルゴリズムが採用されている方式に匹敵するような高圧縮率は達成できません。",
    "１１時でしたら行けます",
    "もし君が時間通りにしたければ、１１時までにそこに着くべきだ。",
    "外形定義ポイントを配置し、ダブルクリックします。",
    "離陸後非常に激しい　嵐だった",
    "他の人のためにものを作ること　それが、彼らへの愛情表現でした",
  ],
  ['Chinese',
    "对了，他们还去了白金汉宫接受了女王的勋章，并且直到现在，或多或少地还是人们接受他们的原因。",
    "那位消防队员从窗户跳了进去。",
    "静候佳音。",
    "当然，也丝毫没意识到在遥远的未来等待着他的紧密的关注。",
    "首先，它基于真实的证据和经验，而且被证明是可以实际运用的。",
    "尽管他爱用“谎话连篇”这种词，却绝不是伪君子。",
    "因此，在度过了一个无眠的夜晚之后，黎明前男朋友带着我去了医院。",
    "它汇集了来自成员国首席统计学家来自世界各地。",
    "比比爱莎目前生活在美国。",
    "你如果吃这么多巧克力就会发胖的。",
  ],
  ['Mandarin',
    "你要呆多久？",
    "她是我最好的朋友。",
    "很遗憾, 我只讲一点中文｡",
    "对不起, 我不讲英语｡",
    "您早, 您讲英语吗?",
    "很高兴认识您｡",
    "这里有人会讲英语吗?",
    "史密斯是王明　的　朋友。",
    "不，那不是杂志。那是字典。",
    "王明是学生。",
  ],
  ['Indonesian',
    "Maaf saya nggak minum minuman manis.",
    "maaf Pak tinggal di kota ini.",
    "Saya ingin mengundang anda makan malam.",
    "Bisakah Anda bercerita lebih banyak tentang Anda?",
    "Bolehkah saya minta nomor telepon Anda?",
    "Apakah itu dalam Bahasa Indonesia?",
    "Berapa lama dari sini ke sana?",
    "Apakah bisa jalan kaki dari sini ke sana?",
    "Budaya dan orang-orangnya sangat menarik.",
    "Jangan lupa tulis surat kepada saya dari waktu ke waktu.",
  ],
  ['Bulgarian',
    "Струва ми се, че времето започна да се променя все повече и повече.",
    "Родителите ми отсъстваха през цялата миналата седмица.",
    "Децата отидоха и играха футбол на стадиона.",
    "Ценете любовта, докато все още я имате, защото в един момент ще я загубите.",
    "Водата кипи при температури над 100 градуса по Целзий.",
    "Твърди се, че тази гора е обитавана от духове от десетилетия.",
    "Селото, в което е израснал дядо ми, е на 60 километра от този град.",
    "Столовете на масата бяха счупени от нашия съсед.",
    "Всеки сезон времето у нас се променя драстично.",
    "Изглежда, че това лекарство е причинило повече вреда, отколкото полза.",
  ],
  ['Hindi',
    "मेरा दिल प्यार की बात कर रहा है",
    "इस शब्द का अंग्रेज़ी में क्या मतलब है?",
    "वहाँ पहुचने में कितनी देर लगती है?",
    "सबसे करीबी दवाई की दुकान कहाँ है?",
    "मैं आपके देश फिरसे आना चाहूँगा",
    "शिक्षा कम से कम प्रारम्भिक और बुनियादी अवस्थाओं में निःशुल्क होगी",
    "प्रत्येक व्यक्ति को किसी भी ऐसी वैज्ञानिक, साहित्यिक या कलास्मक कृति मे उत्पन्न नैतिक और आर्थिक हितों की रक्षा का अधिकार है जिसका रचयिता वह स्वयं हो।",
    "प्रत्येक व्यक्ति को स्वतन्त्रतापूर्वक समाज के सांस्कृतिक जीवन में हिस्सा लेने",
    "शिक्षा का उद्देश्य होगा मानव व्यक्तित्व का पूर्ण विकास और मानाव अधिकारों तथा बुनियादी स्वतन्त्रताओं के प्रति सम्मान को पुष्टि",
    "शिक्षा द्वारा राष्ट्रों, जातियों अथवा घार्मिक समूहों के बीच आपसी सद्भावना",
  ],
  ['Bengali',
    "আপনার সাথে দেখা হয়ে ভালো লাগলো।",
    "আপনি কি বাংলা ছাড়া অন‍্য কোনও ভাষা বলতে পারেন?",
    "আমার সাথে বাংলায় কথা বলো।",
    "আপনি আমার সঙ্গে নাচবেন?",
    "আমার হভারক্রাফ্ট কুঁচে মাছ-এ ভরা হয়ে গেছে",
    " প্রত্যেকের‌ই শিক্ষালাভের অধিকার রয়েছে।",
    "আমার মায়ের বানানো চকলেট কেক আমার খুব প্রিয়।",
    "আমাদের গ্রহটি বেশিরভাগ জল দ্বারা আবৃত।",
    "সবুজ উদ্ভিদ হল সেই সব উদ্ভিদ যা সালোকসংশ্লেষণের প্রক্রিয়া চালায়।",
    "এই সময়ের মধ্যে আমি যে বইগুলি পড়ি তা হল অ্যাডভেঞ্চার এবং অ্যাকশন বই।",
  ],
  ['Hungarian',
    "Szeretnélek meghívni vacsorázni.",
    "Mario a múlt héten indult el otthonról, és holnap érkezik meg úti céljára.",
    "Néhány internetes oldal az idősek megsegítésére jött létre.",
    "Néhány város építészete hihetetlenül gyönyörű.",
    "Az ágy abban a szállodában, ahol megszálltunk, nagyon kényelmes volt.",
    "Nekem úgy tűnik, hogy a család Ukrajnából érkezett az elmúlt hónapokban.",
    "Amikor elkezdődött az egyetem, csodálatos napokat éltem át.",
    "Ma este a gimnáziumi barátaimmal fogok találkozni.",
    "A futball a legkedveltebb sport a bolygón, és ezt követi a legtöbb ember.",
    "Nagyszüleim elmentek nyaralni a hegyekbe, egy jól ismert romániai üdülőhelyre.",
  ],
  ['Arabic',
    "لن يذهب أي شخص إلى العرض لأكثر من 3 أيام.",
    "الهاتف الذي اشتراه لي والدي مكسور بعد شهر واحد فقط.",
    "نفدت بطاريات جهاز التحكم عن بعد الخاص بالتلفزيون.",
    "كان هذا المنتج الموسيقي معروفًا بسبب جولة حول العالم.",
    "يجب ألا تتخلى عن الحب أبدًا ، بغض النظر عما يحدث.",
    "اتصلت بي أمي للذهاب إلى أجدادي ومساعدتهم.",
    "الأصدقاء الحقيقيون سيكونون قريبين منك في أي موقف.",
    "افتقد الأوقات التي كنا نخرج فيها ونضحك على كل نكتة",
    "سيكون عشاق أفلام Marvel في مفاجأة كبيرة هذا العام.",
    "الملابس التي كنت أرتديها عندما كنت طفلة موجودة في تلك الخزانة.",
  ],
  ['Estonian',
    "Sinu osa on kakskümmend dollarit.",
    "Miks peaks Tom tahtma midagi sellist teha?",
    "Ma ei teadnud, mida talle öelda.",
    "See härra maksab kõige eest.",
    "Ma ei kuulnud telefoni märguandeid, seega ma ei teadnud, et sa tuled.",
    "Arstid on alati huvitatud oma patsientide taastumisest.",
    "Minu loodud rakendus on esimene, mille ma Play poes käivitan.",
    "Täna hommikul ütles kolleeg, et mine metsa matkale.",
    "Ma ei käinud enam Dej's kohatud kolleegidega väljas.",
    "Olen üllatunud, et Rumeenia jalgpallimeeskonnad on nii nõrgad.",
  ],
];